### ISSUE TITLE
add maxAge

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/redis-lru#1]
allow items to expire after a period of time, both with a global option for the cache and individually when setting a key. Also add a `stale` option to decide if stale items should be returned or not when available.

**Comment by icebob** [comment]
_Good project. This is exactly what I'm searching for my project. Keep good work!_

**Comment by facundoolano** [comment]
I could make this work the same as node-lru-cache by setting expiration on values saved in Redis, and assuming anything that comes as `null` has expired. But, even if it's the same behaviour as node-lru-cache I'm not too happy with it since it introduces inconsistencies (i.e. least recently accessed items will be evicted before stale ones, will appear in the keys array, cache count, etc.).

**Comment by facundoolano** [comment]
then again it would still be useful in case you need to make sure stale data is not being served anymore.
