### ISSUE TITLE
Node 4 support.

### ISSUE THREAD

**Issue by offero** [facundoolano/redis-lru#7]
I see the use of the ... operator, but that's not node 4 compatible. Can you make the library node 4 compatible?

**Comment by facundoolano** [comment]
Ok, that's a fair request, I'll change that when I get some time. Any other spot where you've noticed incompatible stuff?

**Comment by facundoolano** [comment]
(BTW you can also send a PR and I'll merge it if it passes the tests)

**Comment by facundoolano** [comment]
Just published the fix, please check if it works for you now.

**Comment by offero** [comment]
Thanks! I'll test it shortly.
